version: '3'

# Build All Base Images
services:
    # Base for display + audio transport
    base-displayaudio:
        image: oldwebtoday/base-displayaudio
        build: ../base-displayaudio

    # VNC + WS AUDIO
    vnc-ws-audio:
        image: oldwebtoday/vnc-ws-audio
        build: ../vnc-ws-audio
        depends_on:
            - base-displayaudio

    # VNC + WetRTC AUDIO
    vnc-webrtc-audio:
        image: oldwebtoday/vnc-webrtc-audio
        build: ../vnc-webrtc-audio
        depends_on:
        - base-displayaudio

